-- Схема данных модуля «Клиенты». Поля типа «Список» вынесены в отдельные справочники;
-- наименования справочников хранятся на трёх языках: русском (name), английском и белорусском.

create table city (
    id      bigint generated by default as identity primary key,
    name    varchar(100) not null unique,
    name_en varchar(100) not null,
    name_be varchar(100) not null
);

create table marital_status (
    id      bigint generated by default as identity primary key,
    name    varchar(100) not null unique,
    name_en varchar(100) not null,
    name_be varchar(100) not null
);

create table citizenship (
    id      bigint generated by default as identity primary key,
    name    varchar(100) not null unique,
    name_en varchar(100) not null,
    name_be varchar(100) not null
);

create table disability (
    id      bigint generated by default as identity primary key,
    name    varchar(100) not null unique,
    name_en varchar(100) not null,
    name_be varchar(100) not null
);

create table client (
    id                    bigint generated by default as identity primary key,
    last_name             varchar(60)  not null,
    first_name            varchar(60)  not null,
    middle_name           varchar(60)  not null,
    birth_date            date         not null,
    sex                   varchar(1)   not null check (sex in ('M', 'F')),
    passport_series       varchar(2)   not null,
    passport_number       varchar(7)   not null,
    issued_by             varchar(200) not null,
    issue_date            date         not null,
    identification_number varchar(14)  not null,
    birth_place           varchar(200) not null,
    residence_city_id     bigint       not null references city,
    residence_address     varchar(200) not null,
    home_phone            varchar(20),
    mobile_phone          varchar(20),
    email                 varchar(100),
    registration_city_id  bigint       not null references city,
    marital_status_id     bigint       not null references marital_status,
    citizenship_id        bigint       not null references citizenship,
    disability_id         bigint       not null references disability,
    pensioner             boolean      not null,
    monthly_income        decimal(14, 2),
    -- последний рубеж защиты от дублей: даже в обход сервиса два одинаковых паспорта не записать
    constraint uq_client_passport unique (passport_series, passport_number),
    constraint uq_client_identification unique (identification_number)
);

create index ix_client_fio on client (last_name, first_name, middle_name);
