-- Схема данных главной книги банка

create table currency (
    code    varchar(3)  primary key,
    name    varchar(60) not null,
    name_en varchar(60) not null,
    name_be varchar(60) not null
);

-- Справочник «План счетов»: балансовый счёт, наименование на трёх языках и активность
create table chart_of_accounts (
    code     varchar(4)   primary key,
    name     varchar(200) not null,
    name_en  varchar(200) not null,
    name_be  varchar(200) not null,
    activity varchar(14)  not null check (activity in ('ACTIVE', 'PASSIVE', 'ACTIVE_PASSIVE'))
);

-- Лицевые счета: 13-значный номер, обороты по дебету и кредиту
create table account (
    id            bigint generated by default as identity primary key,
    number        varchar(13)    not null unique,
    chart_code    varchar(4)     not null references chart_of_accounts,
    currency_code varchar(3)     not null references currency,
    name          varchar(200)   not null,      -- ФИО клиента либо код наименования счёта банка
    owner_code    int            not null,      -- код клиента, 0 — счёт самого банка
    owner_seq     int            not null,      -- порядковый номер счёта у владельца
    contract_ref  varchar(40),                  -- договор, в рамках которого открыт счёт
    debit         decimal(19, 2) not null default 0,
    credit        decimal(19, 2) not null default 0,
    opened_on     date           not null,
    constraint uq_account_owner unique (owner_code, owner_seq)
);

create index ix_account_contract on account (contract_ref);

-- Ключи идемпотентности: повтор запроса с тем же ключом не создаёт проводки второй раз
create table posting_batch (
    batch_key  varchar(80) primary key,
    created_at timestamp   not null
);

-- Журнал операций и строки проводок
create table operation (
    id           bigint generated by default as identity primary key,
    batch_key    varchar(80)  not null references posting_batch,
    bank_date    date         not null,
    description  varchar(200) not null,          -- код названия операции: текст подставляется при чтении
    contract_ref varchar(40),
    created_at   timestamp    not null
);

create table operation_entry (
    id           bigint generated by default as identity primary key,
    operation_id bigint         not null references operation,
    account_id   bigint         not null references account,
    side         varchar(6)     not null check (side in ('DEBIT', 'CREDIT')),
    amount       decimal(19, 2) not null check (amount > 0)
);

create index ix_entry_account on operation_entry (account_id);

-- Текущий открытый банковский день (одна строка)
create table bank_day (
    id        int  primary key,
    bank_date date not null
);
