-- Схема данных сервиса депозитов

-- Справочник депозитных программ («вид депозита»); название и описание — на трёх языках
create table deposit_product (
    id               bigint generated by default as identity primary key,
    name             varchar(100)   not null,
    name_en          varchar(100)   not null,
    name_be          varchar(100)   not null,
    kind             varchar(12)    not null check (kind in ('REVOCABLE', 'IRREVOCABLE')),
    currency         varchar(3)     not null,
    rate             decimal(6, 2)  not null,
    min_amount       decimal(19, 2) not null,
    min_term_months  int            not null,
    max_term_months  int            not null,
    description      varchar(300)   not null,
    description_en   varchar(300)   not null,
    description_be   varchar(300)   not null
);

create table deposit_contract (
    id               bigint generated by default as identity primary key,
    number           varchar(20)    not null unique,
    product_id       bigint         not null references deposit_product,
    client_id        bigint         not null,          -- клиент из модуля «Клиенты» (ЛР1)
    client_name      varchar(200)   not null,
    currency         varchar(3)     not null,
    amount           decimal(19, 2) not null,
    rate             decimal(6, 2)  not null,
    term_months      int            not null,
    start_date       date           not null,
    end_date         date           not null,
    main_account     varchar(13)    not null,          -- счёт основной суммы вклада
    interest_account varchar(13)    not null,          -- счёт процентов по вкладу
    status           varchar(8)     not null check (status in ('ACTIVE', 'CLOSED')),
    accrued          decimal(19, 2) not null default 0,   -- начислено процентов
    paid             decimal(19, 2) not null default 0,   -- выплачено процентов
    paid_months      int            not null default 0,   -- оплачено полных месяцев
    closed_on        date
);

create index ix_deposit_client on deposit_contract (client_id);
