-- Схема данных сервиса кредитов

-- Справочник кредитных программ («вид кредита»); название и описание — на трёх языках
create table credit_product (
    id               bigint generated by default as identity primary key,
    name             varchar(100)   not null,
    name_en          varchar(100)   not null,
    name_be          varchar(100)   not null,
    kind             varchar(14)    not null check (kind in ('ANNUITY', 'INTEREST_ONLY')),
    currency         varchar(3)     not null,
    rate             decimal(6, 2)  not null,
    min_amount       decimal(19, 2) not null,
    max_amount       decimal(19, 2) not null,
    min_term_months  int            not null,
    max_term_months  int            not null,
    description      varchar(300)   not null,
    description_en   varchar(300)   not null,
    description_be   varchar(300)   not null
);

create table credit_contract (
    id               bigint generated by default as identity primary key,
    number           varchar(20)    not null unique,
    product_id       bigint         not null references credit_product,
    client_id        bigint         not null,          -- клиент из модуля «Клиенты» (ЛР1)
    client_name      varchar(200)   not null,
    currency         varchar(3)     not null,
    amount           decimal(19, 2) not null,
    rate             decimal(6, 2)  not null,
    term_months      int            not null,
    start_date       date           not null,
    end_date         date           not null,
    main_account     varchar(13)    not null,          -- текущий (кредитный) счёт клиента
    interest_account varchar(13)    not null,          -- счёт процентов по кредиту
    status           varchar(8)     not null check (status in ('ACTIVE', 'CLOSED')),
    principal_paid   decimal(19, 2) not null default 0,
    interest_paid    decimal(19, 2) not null default 0,
    closed_on        date
);

-- График платежей по кредиту
create table payment_item (
    id            bigint generated by default as identity primary key,
    contract_id   bigint         not null references credit_contract,
    seq           int            not null,
    due_date      date           not null,
    principal     decimal(19, 2) not null,
    interest      decimal(19, 2) not null,
    balance_after decimal(19, 2) not null,             -- остаток долга после платежа
    paid_on       date,
    constraint uq_payment_item unique (contract_id, seq)
);

-- Банковская карта к кредитному счёту (ЛР4). PIN-код хранится только в виде BCrypt-хеша
create table card (
    id              bigint generated by default as identity primary key,
    number          varchar(16)  not null unique,
    contract_id     bigint       not null unique references credit_contract,
    holder          varchar(200) not null,
    pin_hash        varchar(80)  not null,
    failed_attempts int          not null default 0,
    blocked         boolean      not null default false
);

-- Справочник операторов мобильной связи
create table mobile_operator (
    code varchar(10) primary key,
    name varchar(60) not null
);

-- Платежи за услуги связи, проведённые через банкомат
create table mobile_payment (
    id          bigint generated by default as identity primary key,
    card_number varchar(16)    not null,
    operator    varchar(10)    not null references mobile_operator,
    phone       varchar(10)    not null,
    amount      decimal(19, 2) not null,
    bank_date   date           not null,
    reference   varchar(40)    not null unique
);
